name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Server
      run: wget https://raw.githubusercontent.com/raiyan8086/script/refs/heads/main/gmail.js
    - run: npm install puppeteer-extra-plugin-stealth puppeteer-extra puppeteer@19.10.0 node-2fa readline axios fs
    - run: node gmail
